
@startuml

class Brand {
  BrandID
  BrandName
}

class PartType {
  PartTypeID
  TypeName
}

class Part {
  PartID
  PartName
  PartTypeID
  BrandID
  Price
  Compatibility
}

class SystemBuild {
  BuildID
  BuildName
}

class BuildPart {
  BuildPartID
  BuildID
  PartID
}



@enduml

